apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  rbd:
    monitors:
    - "{{ ip:port }}"
    - "{{ ip:port }}"
    - "{{ ip:port }}"
    pool: "{{ ceph-pool-name }}"
    image: "{{ imgage-name }}"
    user: admin
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
