apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: ceph.com/rbd
  finalizers:
  - kubernetes.io/pvc-protection
  name: test-pvc-dy
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: test-storageclass
  volumeMode: Filesystem