apiVersion: v1
kind: Pod
metadata:
    name: test-pod
spec:
    containers:
    - name: container-1
      image: ubuntu:18.04
      volumeMounts:
      - name: cache-volume
        mountPath: /cache
        subPath: cache1
      - name: hostpath-volume
        mountPath: /data
        readOnly: true
    - name: container-2
      image: ubuntu:18.04
      volumeMounts:
      - name: cache-volume
        mountPath: /cache
        subPath: cache2 #宿主机上的子目录(用于区分 pod 中的多个容器)
    volumes:
    - name: cache-volume
      emptyDir: {} # 运行 pod 时在宿主机上创建临时目录, pod 删除后宿主机目录也删除
    - name: hostpath-volume
      hostPath: # 将宿主机目录挂载到 pod 上, pod 删除后宿主机目录不变
        path: /tmp/data
