apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  name: test-storageclass
parameters:
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: ceph
  fsType: xfs
  imageFeatures: layering
  imageFormat: "2"
  monitors: 172.16.14.157:6789,172.16.14.149:6789,172.16.14.147:6789
  pool: k8s
  userId: admin
  userSecretName: ceph-secret
  userSecretNamespace: ceph
provisioner: ceph.com/rbd
reclaimPolicy: Delete
volumeBindingMode: Immediate