apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
  replicas: 2
  selector:
     app: rc-pod
  template:
    metadata:
      labels:
        app: rc-pod
    spec:
      containers:
      - name: rc-pod
        image: nginx
        ports:
        - name: http
          containerPort: 80