apiVersion: v1
kind: Pod
metadata:
  name: secretexample
spec:
  containers:
  - name: secretexample
    image: busybox
    command: ["/bin/sh", "-c", "echo user_name:$(USER) password:$(PASS)"]
    env:
    - name: USER
      valueFrom:
        secretKeyRef:
          name: webserver-credentails
          key: username.txt
    - name: PASS
      valueFrom:
        secretKeyRef:
          name: webserver-credentails
          key: password.txt