# 通过 Volume 可以实现节点上的目录与 pod 上的目录相互关联的功能
# Kubernetes 提供两类存储卷: Basic Volume, Persistent Volume
# Basic Volume 通常用于单 pod 中容器存储共享，生命周期与 pod 相同
# Persistent Volume 通常用于将容器中的数据持久化，pod 删除后数据依然存在

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  volumes:
  - name: sharedspace  # 将宿主机上的路径与 volume_name 建立映射关系
    hostPath:
      path: "/var/sharedPodDir"
  containers:
  - name: nginx
    image: nginx:1.7.9
    volumeMounts:
    - mountPath: "/containerMount" # 将容器内的路径与 volume_name 建立映射关系
      name: "sharedspace"
    ports:
    - containerPort: 80