apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: wp
    image: wordpress
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
        ephemeral-storage: "2Gi" # 临时存储
      limits:
        memory: "128Mi"
        cpu: "500m"
        ephemeral-storage: "4Gi"
