apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default
secrets:
- name: default_secret
---
apiVersion: v1
kind: Secret
metadata:
  name: default_secret
  namespace: default
type: kubernetes.io/service-account-token
data:
  ca.crt:
  namespace:
  token:
