---

- name: Install Kafka And Start Service
  hosts: kafka

  vars_files:
    - vars.yml
  tasks: 
    - name: Copy And Extract JDK Install Packages
      unarchive: src={{ pkg_path }}/{{ jdk_pkg }} dest=/tmp
      
    - name: Create Directory If Not Exist.
      file: 
        path: /usr/local/services
        state: directory
        mode: 0755

    - name: Install Jdk
      shell: "cd /tmp && bash +x {{ jdk_install_shell }}"
      register: install_result
      ignore_errors: true
    
    - debug: msg={{ install_result }}

    - assert:
        that: install_result.rc == 0
        msg: "Install Jdk returned non-zero, check please"
    
    - name: Copy And Extract Kafka Install Packages
      unarchive: src={{ pkg_path }}/{{ kafka_pkg }} dest={{ install_path }}

    - name: Copy server.properties File to Host
      template:
        src: server.properties.j2
        dest: "{{ kafka_path }}/config/server.properties"
        owner: root
        group: root
        mode: 0644

    - name: add /etc/profile
      lineinfile: dest=/etc/profile regexp="^KAFKA_HOME=" line="KAFKA_HOME={{ kafka_path }}"
    - name: add /etc/profile
      lineinfile : dest=/etc/profile regexp="^export KAFKA_HOME" line="export KAFKA_HOME"  

    - name: add /etc/profile
      lineinfile: dest=/etc/profile regexp="^PATH=" line="${KAFKA_HOME}/bin:$PATH"
    - name: add /etc/profile
      lineinfile : dest=/etc/profile regexp="^export PATH" line="export PATH"  
    
    - name: add /etc/profile
      lineinfile: dest=/etc/profile regexp="^KAFKA_CONF_DIR=" line="KAFKA_CONF_DIR=${KAFKA_HOME}/config"
    - name: add /etc/profile
      lineinfile : dest=/etc/profile regexp="^export KAFKA_CONF_DIR" line="export KAFKA_CONF_DIR"
    
    - name: Start kafka
      shell: "cd {{ kafka_path }}  && bin/kafka-server-start.sh -daemon config/server.properties "
      when: inventory_hostname in groups['kafka']
    
    - name: Jps
      shell: "{{ java_path }}/bin/jps"
    
    - name: Check kafka is running
      shell: "{{ java_path }}/bin/jps | grep Kafka"
      when: inventory_hostname in groups['kafka']
    
    - name: Test Create a topic named test
      shell: "{{ kafka_path }}/bin/kafka-topics.sh --create --zookeeper {{ groups['zk'][0]}}:2181 --replication-factor 2 -partitions 1 --topic test"
      when: inventory_hostname == groups['kafka'][0]