---
- hosts: node
  tasks:
  - name: Create necessary directories
    file: path=/data/kubernetes/{{ item }} state=directory
    with_items:
    - bin
    - conf
    - cfssl
  - name: Unarchive install packages
    unarchive:
      src: pkgs/flannel-v0.10.0-linux-amd64.tar.gz
      dest: /data/kubernetes/bin
      mode: 0755
  - name: Copy the certificates
    copy:
      src: conf/{{ item }}*pem
      dest: /data/etcd/cfssl
    with_items:
    - etcd
    - ca
  - name: Upload flanneld config
    template:
      src: config/flanneld.j2
      dest: /data/kubernetes/conf/flanneld
      mode: 0644
  - name: Upload flanneld.service
    copy:
      src: config/flanneld.service
      dest: /usr/lib/systemd/system/flanneld.service
      mode: preserve
  - name: Start flanneld service
    systemd:
      daemon_reload: true
      name: flanneld
      enabled: true
      state: started
  - name: add kubernetes home into /etc/profile
    lineinfile: dest=/etc/profile regexp="^KUBERNETES_HOME="line="KUBERNETES_HOME='/data/kubernetes/'"
  - name: export kubernetes
    lineinfile : dest=/etc/profile regexp="^exportKUBERNETES_HOME" line="export KUBERNETES_HOME/bin"