---
- hosts: all
  tasks:
  - name: Close firewalld && disable start on boot
    systemd: name=firewalld state=stopped enabled=false
  - name: Clean iptables rules
    shell: iptables -F
  - name: Disable selinux
    shell: /sbin/setenforce 0
  - name: Replace /etc/selinux/config
    copy:
      src: config/etc.selinux.config
      dest: /etc/selinux.config
      mode: preserve
  - name: Close network manager
    systemd: name=NetWorkManager state=stopped enabled=false
  - name: Replace /etc/sysctl.conf
    copy:
      src: config/etc.sysctl.conf
      dest: /etc/sysctl.conf
      mode: preserve
  - name: Load br_netfilter module
    shell: modprobe br_netfilter
  - name: sysctl -p
    shell: sysctl -p
  - name: Close swap
    shell: swapoff -a && sysctl -w vm.swappiness=0
  - name: Install daily tools
    yum: name={{ item }} state=installed
    with_items:
    - sysstat
    - iotop
    - net-tools
    - vim
    - telnet
    - lrzsz
    - mlocate
    - tcpdump
    - ntpdate
    - bzip2
    - gcc
    - screen
    - wget
    - yum-utils
