---
- hosts: node
  tasks:
  - name: Upload docker.repo
    copy:
      src: conf/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
  - name: Install Docker-dependence
    yum:
      name: {{ item }}
      state: installed
    with_items:
    - device-mapper-persistent-data
    - lvm2
  - name: Install Docke-ce
    yum: name=docker-ce state=installed
  - name: Upload /etc/docker/daemon.json
    copy:
      src: config/daemon.json
      dest: /etc/docker/daemon.json
  - name: Unarchive kubernetes-node-linux-adm64.tar.gz
    unarchive:
      src: pkgs/kubernetes-node-linux-adm64.tar.gz
      dest: /data/kubernetes/bin
      mode: 0755
  - name: Copy the certificates
    copy:
      src: conf/{{ item }}*pem
      dest: /data/kubernetes/cfssl
    with_items:
    - ca
    - kube-apiserver
    - kube-proxy
  - name: Copy .kubeconfig
    copy:
      src: conf/{{ item }}.kubeconfig
      dest: /data/kubernetes/cfssl
    with_items:
    - bootstrap
    - kube-proxy
  - name: Upload kubelet.config
    template:
      src: conf/kubelet.config.j2
      dest: /data/kubernetes/conf/kubelet.config
      mode: 0644
  - name: Upload kubelet config
    template:
      src: conf/kubelet.j2
      dest: /data/kubernetes/conf/kubelet
      mode: 0644
  - name: Upload kubelet.service
    copy:
      src: conf/kubelet.service
      dest: /usr/lib/systemd/system/kubelet.service
  - name: start kubelet
    systemd:
      daemon_reload: true
      name: kubelet
      state: startted
      enabled: true
  - name: Upload kube-proxy config
    template:
      src: conf/kube-proxy.j2
      dest: /data/kubernetes/conf/kube-proxy
      mode: 0644
  - name: Upload kube-proxy.service
    copy:
      src: conf/kube-proxy.service
      dest: /usr/lib/systemd/system/kube-proxy.service
  - name: start kube-proxy
    systemd:
      daemon_reload: true
      name: kube-proxy
      state: startted
      enabled: true